[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # ensure the module is loaded from root node_modules at runtime
  external_node_modules = ["@supabase/supabase-js", "googleapis"]

[build.environment]
  NODE_VERSION = "20"

# Enforce HTTPS & basic headers
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"

# Catch-all relay for SEOBoss API
[[redirects]]
  from = "/seoboss/api/*"
  to = "/.netlify/functions/relay/seoboss/api/:splat"
  status = 200
  force = true

# Vault endpoints (App Proxy → Functions)
[[redirects]]
  from = "/apps/engine/v3/vault/list"
  to = "/.netlify/functions/vault-list"
  status = 200
  force = true

  [[redirects]]
  from = "/apps/engine/v3/vault/add"
  to = "/.netlify/functions/vault-add"
  status = 200
  force = true

[[redirects]]
  from = "/apps/engine/v3/vault/update"
  to = "/.netlify/functions/vault-update"
  status = 200
  force = true

# Vault endpoints (App Proxy → Functions)
[[redirects]]
  from = "/apps/engine/v3/vault/delete"
  to   = "/.netlify/functions/vault-delete"
  status = 200
  force = true


# App Proxy → Engine Proxy function
[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/engine-proxy/:splat"
  status = 200
  force = true



  # Vault endpoints that Shopify App Proxy actually forwards to your site
[[redirects]]
  from = "/v3/vault/list"
  to = "/.netlify/functions/vault-list"
  status = 200
  force = true

[[redirects]]
  from = "/v3/vault/add"
  to = "/.netlify/functions/vault-add"
  status = 200
  force = true

[[redirects]]
  from = "/v3/vault/update"
  to = "/.netlify/functions/vault-update"
  status = 200
  force = true

# (Optional convenience if you ever hit them directly)
[[redirects]]
  from = "/v3/vault/delete"
  to   = "/.netlify/functions/vault-delete"
  status = 200
  force = true


[[redirects]]
  from = "/apps/engine/v3/vault/add"
  to = "/.netlify/functions/vault-add"
  status = 200
  force = true

[[redirects]]
  from = "/apps/engine/v3/vault/update"
  to = "/.netlify/functions/vault-update"
  status = 200
  force = true
