# netlify.toml (root of the deployed site)

[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Admin SPA
[[redirects]]
  from = "/admin/*"
  to   = "/admin/index.html"
  status = 200

# ✅ Primary: App Proxy catch-all → relay
[[redirects]]
  from = "/apps/engine/*"
  to   = "/.netlify/functions/relay/:splat"
  status = 200
  force = true

# (Optional) If Shopify ever forwards without the prefix for some reason
[[redirects]]
  from = "/engine/*"
  to   = "/.netlify/functions/relay/:splat"
  status = 200
  force = true
